### ISSUE TITLE
Font size too small!!!!

### ISSUE THREAD

**Issue by throp** [thycotic/cm-docs#26]
Document: (https://docs.thycotic.com/cm/1.3.0)

I'm using Thycotic Connection Manager version 1.3.1.  The font size is incredibly small, and it does not seem like there's any way to make it bigger.  

![image](https://user-images.githubusercontent.com/1637796/93888832-7ecf8c80-fcb6-11ea-89a7-cd364312c1e1.png)

**Comment by danigran** [comment]
Hi, 
While logged into Connection Manager, you can change the default font and size under Global Settings:
![image](https://user-images.githubusercontent.com/46493756/93937027-0f2cc200-fcf5-11ea-8de9-f6c50fe6762b.png)

However, without being signed in the default will always be used. We have an FR open to address this in the future.

Thank you for contacting and using our doc change request feature on the documentation portal.
