### ISSUE TITLE
Not showing all versions.

### ISSUE THREAD

**Issue by mattboyce2000** [thycotic/cm-docs#33]
Document: (https://docs.thycotic.
![2021-03-04_10-40-51](https://user-images.githubusercontent.com/45846428/109952753-1958e080-7cd7-11eb-8358-bec66b8f56bc.jpg)
com/cm/1.5.0/release-notes)

It lists all the versions on the left hand side but not when you click on the link to take you to release notes.

**Comment by danigran** [comment]
This has been fixed with the latest documentation update.

Thank you for your comment.
